name: Blog posts on ReadMe

# Runs every day at 2am UTC
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
    # new action plugin start
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://renjujv.github.io/rss.xml'
          file: 'README.md'
      - uses: sarisia/actions-commit@master
        with:
          github_token: ${{ secrets.PAT }}
    # new action plugin end
    # old action plugin start
#       - name: Get RSS Feed
#         uses: kohrongying/readme-the-rss@master
#         with:
#           feed_url: https://renjujv.github.io/rss.xml
#           count: 10
#       - name: Commit file changes
#         run: |
#             git config --global user.name 'renjujv'
#             git config --global user.email 'renjujv@gmail.com'
#             git add .
#             git diff --quiet --cached || git commit -m "Update README"
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.PAT }}
    # old action plugin end
