name: Blog posts on ReadMe

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://renjujv.github.io/rss.xml'
          file: 'README.md'
      - uses: sarisia/actions-commit@master
#         with:
#           github_token: ${{ secrets.PAT }}
